version: "3"
services:
  prometheus:
    ports:
      - 9090:9090
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    ports:
      - 3000:3000
    image: grafana/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
